---
parserOptions:
  ecmaVersion: 9
  sourceType: module
  ecmaFeatures: {}
env:
  browser: true
  worker: true
  serviceworker: true
  es6: true
extends: eslint:recommended
rules:
  semi:
    - error
    - always
  quotes:
    - error
    - single
  object-curly-newline:
    - error
    - multiline
  object-curly-spacing:
    - error
    - always
  arrow-body-style:
    - error
    - as-needed
  curly:
    - error
    - all
  dot-location:
    - error
    - property
  eqeqeq:
    - error
    - always
  array-bracket-newline:
    - error
    - multiline
  array-bracket-spacing:
    - error
    - always
  array-element-newline:
    - error
    - multiline
  eol-last:
    - error
    - always
  function-paren-newline:
    - error
    - multiline
  multiline-ternary:
    - error
    - always
  newline-per-chained-call: error
  require-atomic-updates: error
  camelcase: error
  brace-style:
    - error
    - allman
  capitalized-comments:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
  func-call-spacing:
    - error
    - never
  implicit-arrow-linebreak:
    - error
    - beside
  indent:
    - error
    - 4
    - switchCase: 1
      variableDeclerator: 1
      memberExpression: 1
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      mode: strict
  keyword-spacing:
    - error
    - before: true
      after: false
  line-comment-position:
    - errpr
    - above
  linebreak-style:
    - error
    - unix
  lines-between-class-members:
    - error
    - ''
  max-depth: error
  max-len: error
  max-lines:
    - warn
    - 600
  max-statements-per-line:
    - error
    - max: 1
  new-cap: error
  no-lonely-if: error
  no-mixed-operators: error
  no-multiple-empty-lines: error
  no-negated-condition: warn
  no-new-object: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  one-var: error
  operator-assignment: error
  operator-linebreak:
    - error
    - before
  padded-blocks:
    - error
    - never
  padding-line-between-statements:
    - error
    - blankline: always
      prev: "*"
      next: break
    - blankline: always
      prev: "*"
      next: return
    - blankline: always
      prev: "*"
      next: case
    - blankline: always
      prev: "*"
      next: default
    - blankline: always
      prev: "*"
      next: throw
  prefer-object-spread: error
  quote-props:
    - error
    - as-needed
  semi-spacing:
    - error
    - before: false
      after: false
  semi-style: error
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  switch-colon-spacing: error
  template-tag-spacing: error
  unicode-bom: error
