notifications:
  email: false
  
language: node_js
node_js: node

deploy:
  provider: npm
  email: "chris@cgames.nl"
  api_key: "qR6q3jRo0HIkZRlmqahMllouX0dKvm0E5qe6xSx8Y63Z/fs+Qq8s03TEvh3qSlNAmk1UPBimdlGFnJzOP0321IxAH3IE+W/usAz6Sez4FIf59NqeSG8+dx5uUMT6tQhnAU4wSJizaNpvoD4et7Z7IPTrOyWX7feC5mEQf2zmoQJfJ8WOl/Yk9hSotoQA7o1YcKjNfMgPYtk1E9nUlPdMajmgzQ+JMgfyNs+/7bqG+67+ZWPHMWO4PWdDVckNFtqgNmZYxHiXAST1Wf554a4EkVnIWQKqbfqCYIGCkX+NZ4f6EQpSCIUquZs307JplmFOU0fDcGxkOeoKgB9yikio2yi/AVW+joJvqq4IJxSAk7nYuKuQHt4rwf8ggcasmi4U5kBgujKbFePGIHypUZmrHPXqhNRu3ged7c9/eNg0Aa0ZG2WCzh7ckW1FX2xH9mAWbmBcsm2Fprdk6YiVP3yKdwk4gpRvWPe56Vi40OfyYKKXnaWutb8xWZ2T+gxSY3LtnuuQyE+uByt/wkEUdXFW2uJRn5RIAtXGzDh037mFdfgQr2ExhXG8/Gcq+nUMsSte8gyImVA1Uk/FdIMM9lW+gq2Qu1CtrxezQzRr3hzjs0F6wkDWtoTElBs/R/8kQzUXDHs94VfxkUaceBiXHAw72lGgBiHECs/5BZZURgvG0gc="
  on:
    tags: true
    branch: master
